version: '3.8'

services:
  change-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - COIN_ONE_CENT=100
      - COIN_FIVE_CENTS=100
      - COIN_TEN_CENTS=100
      - COIN_TWENTY_FIVE_CENTS=100
